name: Cross-Platform Build

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Build for both Linux and Windows

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment for Linux and Windows
      - name: Set up build environment
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            echo "Setting up for Windows"
            # Windows setup (if any)
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            echo "Setting up for Linux"
            chmod +x ./linux-build.sh
          fi

      # Run build for Linux and Windows
      - name: Run build script
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            ./windows-build.cmd  # Use a separate Windows build script if necessary
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            ./linux-build.sh
          fi

      # Upload artifacts for Linux
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Banking-System-x86_64-Linux.bin
          path:  ./Banking-System-x86_64-Linux.bin


      # Upload artifacts for both Windows
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Banking-System-x86_64-Windows.exe
          path: ./Banking-System-x86_64-Windows.exe